services:
  postgres:
    image: 'postgres:latest'
    container_name: 'banking-postgres'
    environment:
      - 'POSTGRES_DB=banking'
      - 'POSTGRES_PASSWORD=banking'
      - 'POSTGRES_USER=banking'
    ports:
      - '5432'

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'banking-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=guest'
      - 'RABBITMQ_DEFAULT_PASS=guest'
    ports:
      - '5672'
      - '15672'