version: '3.8'
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'banking-postgres'
    environment:
      - POSTGRES_DB=banking
      - POSTGRES_PASSWORD=banking
      - POSTGRES_USER=banking
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U banking"]
      interval: 5s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: 'rabbitmq:latest'
    container_name: 'banking-rabbitmq'
    environment:
      - 'RABBITMQ_DEFAULT_USER=banking'
      - 'RABBITMQ_DEFAULT_PASS=banking'
    ports:
      - '5672:5672'