spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/banking
    username: banking
    password: banking
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=5m

resilience4j:
  circuitbreaker:
    instances:
      exchangeRate:
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 10s
  retry:
    instances:
      exchangeRate:
        maxAttempts: 3
        waitDuration: 500ms

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha